# Generated by Django 3.2.23 on 2023-12-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.FileField(upload_to='musics_f'),
        ),
    ]
