# Generated by Django 3.2.23 on 2023-12-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='text',
            field=models.FileField(blank=True, null=True, upload_to='musics_f'),
        ),
    ]
