# Generated by Django 3.2.23 on 2023-12-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='text',
            field=models.FileField(blank=True, null=True, upload_to='texts'),
        ),
    ]
