# Generated by Django 3.2.23 on 2023-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='musics_f/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='text',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='texts/'),
        ),
    ]
