# Generated by Django 3.2.23 on 2023-12-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20231216_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='musics',
            field=models.ManyToManyField(related_name='artist_musics', to='music.Music'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(related_name='mus_artists', to='music.Artist'),
        ),
    ]
