# Generated by Django 3.2.23 on 2023-12-17 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20231216_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='musics_f/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='music',
            name='text',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='texts/', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
    ]
