# Generated by Django 3.2.23 on 2023-12-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20231217_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='artist-profile/'),
        ),
        migrations.AddField(
            model_name='music',
            name='music_img',
            field=models.ImageField(blank=True, null=True, upload_to='music-profile/'),
        ),
    ]
