# Generated by Django 3.2.23 on 2023-12-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20231217_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_img',
            field=models.ImageField(blank=True, default='artist-profile/default.jpg', null=True, upload_to='artist-profile/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_img',
            field=models.ImageField(blank=True, default='music-profile/default.jpg', null=True, upload_to='music-profile/'),
        ),
    ]
