# Generated by Django 3.2.23 on 2023-12-18 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20231217_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='text',
            field=models.FileField(blank=True, null=True, upload_to='texts/', validators=[django.core.validators.FileExtensionValidator(['txt'])]),
        ),
    ]
